version: '2.4'

# Edit these volume mounts to suite
services:
  haproxy:
    volumes:
      - ./local/etc/haproxy/:/usr/local/etc/haproxy
  keepalived:
    environment:
      KEEPALIVE_STATE: master
    volumes:
      - ./local/etc/keepalived/:/etc/keepalived
