version: '2.4'

# Edit these volume mounts to suite
services:
  haproxy:
    volumes:
      - ./local/etc/haproxy/:/usr/local/etc/haproxy
  keepalived:
    volumes:
      - ${pwd}/local/etc/keepalived/master.conf:/etc/keepalived/keepalived.conf
