FROM alpine:3.14

ENV KEEPALIVE_STATE=master

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

RUN apk add --no-cache keepalived && \
    rm -rf /etc/keepalived/keepalived.conf && \
    chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT '/usr/local/bin/entrypoint.sh'
